### PR TITLE
Change Belinvestbank parser accordingly with new site design

### PR DESCRIPTION
**Pull request by jekhor**

### CODE REVIEW

**Comment by abitrolly** [comment]
I am interested to move this to https://bib.openapi.by? What is needed to get this done?

**Comment by jekhor** [comment]
Pick up the lib/bib.rb

ср, 24 кра 2019, 05.26 карыстальнік Anatoli Babenia <
notifications@github.com> напісаў:

**Comment by abitrolly** [comment]
Which license to use?

**Comment by abitrolly** [comment]
https://github.com/openapiby/bib.openapi.by

**Pull request merged**
