### PR TITLE
Chart page: transaction condition and order fix

### PR DESCRIPTION
**Pull request by yahor**

### CODE REVIEW

**Comment by abitrolly** [comment]
That's too boring to review without before/after screens. (

**Comment by yahor** [comment]
@abitrolly it works, trust me ;)

**Comment by abitrolly** [comment]
It works, yes, but is still so booooring..

**Comment by yahor** [comment]
@abitrolly don't worry. me and @jekhor tested this issue before and after fix/deploy.

**Comment by abitrolly** [comment]
image

**Pull request merged**
