### PR TITLE
style: change footer icon size

### PR DESCRIPTION
**Pull request by MoskKir**

### CODE REVIEW

**Comment by abitrolly** [comment]
Pasting screenshot before and after greatly speeds up the review. On Linux (GNOME) you can use <kbd>Ctrl+Shift+PrtSc</kbd> and <kbd>Ctrl+V</kbd>.

**Comment by MoskKir** [comment]
before
image

after
image

**Comment by abitrolly** [comment]
@MoskKir could you rebase this PR to make tests pass? (I fixed them in `master`)

**Comment by cardamo** [comment]
@abitrolly let's teach Travis to build a PR's merge commit instead of head? I mean fetching refs like this for build:

```
git fetch origin refs/pull/404/merge
```

**Comment by abitrolly** [comment]
@cardamo I don't see any setting in Travis  to do this. Besides, rebasing is a common operation that is often needed.

**Pull request merged**
